calculator: main.o addition.o division.o print_result.o
	g++ main.o addition.o division.o print.o -o calculator

main.o: main.cpp
	g++ -c main.cpp

addition.o: addition.cpp
	g++ -c addition.cpp

division.o: division.cpp
	g++ -c division.cpp

print_result.o: print.cpp
	g++ -c print.cpp
